version: "2"
services:
  mongo:
    container_name: nextapi_mongo
    build:
      context: ./.mongo
    ports:
      - "27017:27017"

  adminMongo:
    container_name: nextapi_adminMongo
    image: adicom/admin-mongo
    depends_on:
      - mongo
    ports:
      - "1234:1234"
    volumes:
      - ./.adminMongo/config:/app/config